# Configure main menu and social menu

[[social]]
    identifier = "youtube"
    name       = "YouTube"
    url        = "https://www.youtube.com/playlist?list=PLvY0gBv2JjRpbwOCO0ZjREWof57ilIFNn"

    [social.params]
        icon = "brand-youtube"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/cloudycounty"

    [social.params]
        icon = "brand-github"
